-- =====================================================
-- MIGRATION: Criar tabela config_transcricao
-- Execute este SQL no Supabase Dashboard > SQL Editor
-- =====================================================

-- Tabela de configuracao de transcricao de audio
CREATE TABLE IF NOT EXISTS config_transcricao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_organizacao BIGINT NOT NULL REFERENCES organizacoes(id) ON DELETE CASCADE,

  -- Escopo: grupo OU categoria (mutuamente exclusivo)
  id_grupo BIGINT REFERENCES grupos(id) ON DELETE CASCADE,
  id_categoria BIGINT REFERENCES categorias(id) ON DELETE CASCADE,

  -- Configuracoes
  modo TEXT NOT NULL DEFAULT 'desativado', -- 'desativado' | 'automatico' | 'manual'
  emoji_gatilho TEXT DEFAULT '✍️',          -- Emoji para transcricao manual

  -- Timestamps
  dt_create TIMESTAMPTZ DEFAULT now(),
  dt_update TIMESTAMPTZ DEFAULT now(),

  -- Constraints
  CONSTRAINT check_escopo CHECK (
    (id_grupo IS NOT NULL AND id_categoria IS NULL) OR
    (id_grupo IS NULL AND id_categoria IS NOT NULL)
  ),
  CONSTRAINT unique_grupo UNIQUE (id_organizacao, id_grupo),
  CONSTRAINT unique_categoria UNIQUE (id_organizacao, id_categoria)
);

-- RLS (Row Level Security)
ALTER TABLE config_transcricao ENABLE ROW LEVEL SECURITY;

-- Politica para SELECT
CREATE POLICY "Usuarios podem ver configs da sua organizacao"
  ON config_transcricao FOR SELECT
  USING (id_organizacao IN (
    SELECT id_organizacao FROM usuarios_sistema WHERE id_usuario = auth.uid()
  ));

-- Politica para INSERT
CREATE POLICY "Usuarios podem inserir configs da sua organizacao"
  ON config_transcricao FOR INSERT
  WITH CHECK (id_organizacao IN (
    SELECT id_organizacao FROM usuarios_sistema WHERE id_usuario = auth.uid()
  ));

-- Politica para UPDATE
CREATE POLICY "Usuarios podem atualizar configs da sua organizacao"
  ON config_transcricao FOR UPDATE
  USING (id_organizacao IN (
    SELECT id_organizacao FROM usuarios_sistema WHERE id_usuario = auth.uid()
  ));

-- Politica para DELETE
CREATE POLICY "Usuarios podem deletar configs da sua organizacao"
  ON config_transcricao FOR DELETE
  USING (id_organizacao IN (
    SELECT id_organizacao FROM usuarios_sistema WHERE id_usuario = auth.uid()
  ));

-- Indices para performance
CREATE INDEX IF NOT EXISTS idx_config_transcricao_org ON config_transcricao(id_organizacao);
CREATE INDEX IF NOT EXISTS idx_config_transcricao_grupo ON config_transcricao(id_grupo) WHERE id_grupo IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_config_transcricao_categoria ON config_transcricao(id_categoria) WHERE id_categoria IS NOT NULL;

-- =====================================================
-- QUERY PARA N8N: Buscar config de transcricao por grupo
-- =====================================================
/*
WITH grupo_info AS (
  SELECT g.id, g.id_organizacao, g.id_categoria
  FROM grupos g
  WHERE g.chat_id_whatsapp = '{{ $json.chatId }}'
),
config_grupo AS (
  SELECT ct.modo, ct.emoji_gatilho
  FROM config_transcricao ct
  JOIN grupo_info gi ON ct.id_grupo = gi.id
  WHERE ct.id_organizacao = gi.id_organizacao
),
config_categoria AS (
  SELECT ct.modo, ct.emoji_gatilho
  FROM config_transcricao ct
  JOIN grupo_info gi ON ct.id_categoria = gi.id_categoria
  WHERE ct.id_organizacao = gi.id_organizacao
)
SELECT
  COALESCE(
    (SELECT modo FROM config_grupo),
    (SELECT modo FROM config_categoria),
    'desativado'
  ) AS modo,
  COALESCE(
    (SELECT emoji_gatilho FROM config_grupo),
    (SELECT emoji_gatilho FROM config_categoria),
    '✍️'
  ) AS emoji_gatilho
FROM grupo_info;
*/
